#page title
page_title                                : Sticker Creator                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1624390578                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Sticker Creator                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Design and share your stickers with your favorite messengers.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Armin Shalchian
your_link                                 : https://shalchian.com
your_city                                 :
email_address                             : armin536@gmail.com
facebook_username                         :                                           
instagram_username                        :
twitter_username                          : arminshalchian
github_username                           : rminsh
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  # Messengers
  - title                                 : Your favorite messengers
    description                           : Publish your stickers on Telegram, Whatsapp and iMessage.
    fontawesome_icon_name                 : comment

  # Tools
  - title                                 : Essential Tools
    description                           : Sticker creator has essential tools to design the awesome stickers.
    fontawesome_icon_name                 : brush
  
  # PencilKit
  - title                                 : Pencil support
    description                           : With the support of PencilKit the canvas is in your hands to draw marvelous things.
    fontawesome_icon_name                 : pencil-alt

  # Photos and Unsplash
  - title                                 : Customize your Photos
    description                           : Import images from your photos or download them directly from Unsplash to edit and customize them for your stickers.
    fontawesome_icon_name                 : image

  # Remove background image
  - title                                 : Remove background with AI
    description                           : Sticker creator has an awesome tool to remove background of your photo that makes it suitable for a beautiful sticker.
    fontawesome_icon_name                 : cut
    


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#EBECF3"

link_color                                : "#EE975B"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#E36E6F"
feature_icons_background_color            : "#FDFDFD"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#FDFDFD"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
